# Generated by Django 5.1.6 on 2025-03-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0002_liga_id_fbref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liga',
            old_name='id_fbref',
            new_name='id_footballAPI',
        ),
    ]
