# Generated by Django 5.1.6 on 2025-03-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='assitencias',
            new_name='asistencias',
        ),
    ]
