# Generated by Django 5.1.7 on 2025-03-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_equipos/')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='ligas.liga')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('partidos_ganados', models.PositiveIntegerField(default=0)),
                ('partidos_empatados', models.PositiveIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveIntegerField(default=0)),
                ('goles_a_favor', models.PositiveIntegerField(default=0)),
                ('goles_en_contra', models.PositiveIntegerField(default=0)),
                ('diferencia_goles', models.IntegerField(default=0)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveBigIntegerField(default=0)),
                ('penaltis_marcados', models.PositiveBigIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveBigIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveBigIntegerField(default=0)),
                ('media_posesion', models.FloatField(default=50.0)),
                ('ultimos_5_partidos', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('maximo_goleador', models.CharField(default='', max_length=255)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='equipos.equipo')),
            ],
        ),
    ]
