# Generated by Django 5.1.6 on 2025-03-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('jugadores', '0001_initial'),
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(related_name='equipos', to='jugadores.jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='ligas.liga'),
        ),
    ]
