# Generated by Django 5.1.6 on 2025-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='goles_marcados',
            new_name='goles_favor',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='jugadores',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ultimo_partido',
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_empatados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_ganados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_perdidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ultimos_5_partidos',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='diferencia_goles',
            field=models.IntegerField(default=0),
        ),
    ]
