# Generated by Django 5.1.7 on 2025-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipo_asistencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticasequipo',
            name='ultimos_5_partidos',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
