# Generated by Django 5.1.6 on 2025-03-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_rename_goles_marcados_equipo_goles_favor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='asistencias',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='diferencia_goles',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='goles_contra',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='goles_favor',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='media_posesion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='partidos_empatados',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='partidos_ganados',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='partidos_jugados',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='partidos_perdidos',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='penaltis_marcados',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tarjetas_amarillas',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tarjetas_rojas',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ultimos_5_partidos',
        ),
        migrations.CreateModel(
            name='EstadisticasEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_ganados', models.PositiveIntegerField(default=0)),
                ('partidos_empatados', models.PositiveIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveIntegerField(default=0)),
                ('goles_favor', models.PositiveIntegerField(default=0)),
                ('goles_contra', models.PositiveIntegerField(default=0)),
                ('diferencia_goles', models.IntegerField(default=0)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveBigIntegerField(default=0)),
                ('penaltis_marcados', models.PositiveBigIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveBigIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveBigIntegerField(default=0)),
                ('media_posesion', models.FloatField(default=50.0)),
                ('partidos_jugados', models.PositiveBigIntegerField(default=0)),
                ('ultimos_5_partidos', models.CharField(default='', max_length=10)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='equipos.equipo')),
            ],
        ),
    ]
