# Generated by Django 5.1.6 on 2025-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_remove_equipo_asistencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticasequipo',
            name='maximo_goleador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
