# Generated by Django 5.1.6 on 2025-03-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_estadisticasequipo_maximo_goleador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticasequipo',
            old_name='goles_contra',
            new_name='goles_a_favor',
        ),
        migrations.RenameField(
            model_name='estadisticasequipo',
            old_name='goles_favor',
            new_name='goles_en_contra',
        ),
    ]
