# Generated by Django 5.1.6 on 2025-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_rename_goles_contra_estadisticasequipo_goles_a_favor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticasequipo',
            name='maximo_goleador',
            field=models.CharField(default='', max_length=255),
        ),
    ]
