# Generated by Django 5.1.6 on 2025-03-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_alter_estadisticasequipo_maximo_goleador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticasequipo',
            name='partidos_jugados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
